Repository readur/readur, pull requests merged in 2025-06, with the labels that each got.

#28 chore/fix-gitignore
  .gitignore
  docker-compose.yml
Labels: size:XS

#29 feat(docs): add document deletion and bulk deletion
  LABEL_TESTING.md
  docker-compose.yml
  frontend/src/App.tsx
  frontend/src/components/Labels/Label.tsx
  frontend/src/components/Labels/LabelCreateDialog.tsx
  frontend/src/components/Labels/LabelSelector.tsx
  frontend/src/components/Labels/__tests__/Label.test.tsx
  frontend/src/components/Labels/__tests__/LabelCreateDialog.test.tsx
  frontend/src/components/Labels/__tests__/LabelSelector.test.tsx
  frontend/src/components/Labels/index.ts
  frontend/src/components/Layout/AppLayout.tsx
  frontend/src/components/Upload/UploadZone.tsx
  frontend/src/components/Upload/__tests__/UploadZone.test.tsx
  frontend/src/hooks/useApi.ts
  frontend/src/pages/DocumentDetailsPage.tsx
  frontend/src/pages/DocumentsPage.tsx
  frontend/src/pages/LabelsPage.tsx
  frontend/src/pages/__tests__/LabelsPage.test.tsx
  frontend/src/services/api.ts
  frontend/src/test/label-test-utils.ts
  migrations/20240620000001_add_labels_system.sql
  migrations/20240620000002_add_assigned_by_to_document_labels.sql
  run_label_tests.sh
  src/db/documents.rs
  src/db_guardrails.rs
  src/file_service.rs
  src/main.rs
  src/models.rs
  src/routes/documents.rs
  src/routes/labels.rs
  src/routes/mod.rs
  src/tests/document_routes_tests.rs
  src/tests/documents_tests.rs
  src/tests/file_service_tests.rs
  src/tests/labels_tests.rs
  src/tests/mod.rs
  test_bulk_delete.rs
  tests/document_deletion_integration_tests.rs
  tests/file_processing_pipeline_tests.rs
  tests/labels_integration_tests.rs
Labels: enhancement, size:XXL

#37 feat(server): normalize etags from webdav to properly check for file …
  migrations/20250623000001_normalize_existing_etags.sql
  src/webdav_xml_parser.rs
  tests/webdav_enhanced_unit_tests.rs
  tests/webdav_sync_tests.rs
Labels: enhancement, size:M

#41 feat(server): implement better error for configuration issues
  src/config.rs
  src/db/sources.rs
  src/main.rs
  src/source_scheduler.rs
  src/webdav_service.rs
  tests/webdav_enhanced_unit_tests.rs
Labels: enhancement, size:XL

#43 feat(server): decrease logging verbosity for ingestion
  Cargo.lock
  Cargo.toml
  src/bin/batch_ingest.rs
  src/document_ingestion.rs
  src/main.rs
  src/source_sync.rs
Labels: enhancement, size:M

#44 feat(client): update/fix dashboard and theme
  frontend/src/components/Dashboard/Dashboard.tsx
  frontend/src/components/EnhancedSnippetViewer/EnhancedSnippetViewer.tsx
  frontend/src/components/MimeTypeFacetFilter/MimeTypeFacetFilter.tsx
  frontend/src/pages/DocumentsPage.tsx
  frontend/src/pages/FailedOcrPage.tsx
  frontend/src/pages/SourcesPage.tsx
  frontend/src/services/api.ts
Labels: enhancement, size:L

#46 fix(server): catch pdf-extract spammy logs
  src/file_service.rs
  src/ocr.rs
Labels: bug, size:S

#54 feat(client): fixup search page and add icons
  frontend/index.html
  frontend/public/favicon.ico
  frontend/public/readur-32.png
  frontend/public/readur-64.png
  frontend/public/readur.png
  frontend/src/components/EnhancedSnippetViewer/EnhancedSnippetViewer.tsx
  frontend/src/components/Layout/AppLayout.tsx
  frontend/src/pages/SearchPage.tsx
Labels: enhancement, size:XL

#63 feat(server): reorganize components into their own modules and fix im…
  frontend/src/components/Labels/__tests__/LabelCreateDialog.test.tsx
  src/bin/batch_ingest.rs
  src/ingestion/batch_ingest.rs
  src/ingestion/document_ingestion.rs
  src/ingestion/mod.rs
  src/lib.rs
  src/main.rs
  src/monitoring/db_monitoring.rs
  src/monitoring/error_management.rs
  src/monitoring/mod.rs
  src/monitoring/request_throttler.rs
  src/ocr/api.rs
  src/ocr/enhanced.rs
  src/ocr/enhanced_processing.rs
  src/ocr/error.rs
  src/ocr/health.rs
  src/ocr/mod.rs
  src/ocr/queue.rs
  src/ocr/tests.rs
  src/routes/documents.rs
  src/routes/metrics.rs
  src/routes/prometheus_metrics.rs
  src/routes/queue.rs
  src/routes/sources.rs
  src/routes/webdav.rs
  src/routes/webdav/webdav_sync.rs
  src/scheduling/mod.rs
  src/scheduling/source_scheduler.rs
  src/scheduling/source_sync.rs
  src/scheduling/watcher.rs
  src/scheduling/webdav_scheduler.rs
  src/services/file_service.rs
  src/services/local_folder_service.rs
  src/services/mod.rs
  src/services/s3_service.rs
  src/services/s3_service_stub.rs
  src/services/webdav_service.rs
  src/test_utils.rs
  src/tests/file_service_tests.rs
  src/tests/helpers.rs
  src/tests/oidc_tests.rs
  tests/auto_resume_tests.rs
  tests/cancellation_tests.rs
  tests/document_upload_hash_duplicate_tests.rs
  tests/hash_duplicate_detection_tests.rs
  tests/ignored_files_integration_tests.rs
  tests/local_folder_sync_tests.rs
  tests/ocr_pipeline_integration_test.rs
  tests/simple_throttling_test.rs
  tests/source_scheduler_simple_tests.rs
  tests/source_scheduler_tests.rs
  tests/source_sync_hash_duplicate_tests.rs
  tests/stop_sync_functionality_tests.rs
  tests/universal_source_sync_tests.rs
  tests/webdav_comprehensive_tests.rs
  tests/webdav_enhanced_unit_tests.rs
  tests/webdav_hash_duplicate_tests.rs
  tests/webdav_integration_tests.rs
  tests/webdav_sync_tests.rs
  tests/webdav_unit_tests.rs
Labels: enhancement, size:L

#64 feat(tests): reorganize unit and integration tests
  tests/integration_admin_functionality_tests.rs
  tests/integration_auto_resume_tests.rs
  tests/integration_cancellation_tests.rs
  tests/integration_comprehensive_source_management_tests.rs
  tests/integration_debug_ocr_test.rs
  tests/integration_document_deletion_integration_tests.rs
  tests/integration_document_upload_hash_duplicate_tests.rs
  tests/integration_error_handling_edge_cases_tests.rs
  tests/integration_failed_ocr_endpoints_tests.rs
  tests/integration_file_processing_pipeline_tests.rs
  tests/integration_hash_duplicate_detection_tests.rs
  tests/integration_ignored_files_integration_tests.rs
  tests/integration_integration_tests.rs
  tests/integration_investigate_empty_content.rs
  tests/integration_labels_integration_tests.rs
  tests/integration_local_folder_sync_tests.rs
  tests/integration_ocr_corruption_tests.rs
  tests/integration_ocr_failure_counting_tests.rs
  tests/integration_ocr_pipeline_integration_test.rs
  tests/integration_ocr_queue_management_tests.rs
  tests/integration_performance_load_tests.rs
  tests/integration_prometheus_metrics_tests.rs
  tests/integration_role_based_access_control_tests.rs
  tests/integration_s3_sync_tests.rs
  tests/integration_simple_throttling_test.rs
  tests/integration_source_scheduler_simple_tests.rs
  tests/integration_source_scheduler_tests.rs
  tests/integration_source_sync_hash_duplicate_tests.rs
  tests/integration_source_update_tests.rs
  tests/integration_stop_sync_functionality_tests.rs
  tests/integration_test_image_ocr_tests.rs
  tests/integration_thread_separation_tests.rs
  tests/integration_universal_source_sync_tests.rs
  tests/integration_webdav_comprehensive_tests.rs
  tests/integration_webdav_hash_duplicate_tests.rs
  tests/integration_webdav_integration_tests.rs
  tests/integration_webdav_sync_tests.rs
  tests/unit_basic_sync_tests.rs
  tests/unit_oidc_unit_tests.rs
  tests/unit_unit_tests.rs
  tests/unit_webdav_enhanced_unit_tests.rs
  tests/unit_webdav_unit_tests.rs
Labels: size:XS

#65 feat(client/server): add a new badge for each source that shows the n…
  frontend/src/pages/SourcesPage.tsx
  src/db/documents.rs
  src/models.rs
  src/routes/sources.rs
Labels: enhancement, size:L

#70 feat(frontend): click to expand preview in document details
  frontend/src/pages/DocumentDetailsPage.tsx
Labels: enhancement, size:S

#71 feat(frontend): view failed document and link to details
  frontend/src/pages/FailedOcrPage.tsx
Labels: enhancement, size:L

#69 fix(server/client): fix incorrect OCR measurements
  Cargo.toml
  frontend/src/pages/FailedOcrPage.tsx
  frontend/src/services/api.ts
  migrations/20250628000001_backfill_ocr_confidence.sql
  src/db/documents.rs
  src/ocr/enhanced.rs
  src/routes/documents.rs
  src/tests/document_routes_tests.rs
  src/tests/documents_tests.rs
  src/tests/enhanced_ocr_tests.rs
  src/tests/generic_migration_tests.rs
  src/tests/helpers.rs
  src/tests/mod.rs
  tests/integration_document_deletion_integration_tests.rs
Labels: bug, size:XXL
